-- Supabase (PostgreSQL) Schema for f(x) factory club site
-- Copy and paste this script into the Supabase SQL Editor (Dashboard > SQL Editor > New query) and click Run.

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  bio TEXT,
  github TEXT,
  join_date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_name TEXT NOT NULL,
  date TEXT NOT NULL,
  session_code TEXT NOT NULL,
  status TEXT DEFAULT 'Present',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT UNIQUE NOT NULL,
  code TEXT NOT NULL,
  topic TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  tech_stack TEXT,
  github_url TEXT,
  author TEXT,
  stars INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  content TEXT NOT NULL,
  date TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  grade INTEGER NOT NULL,
  email TEXT NOT NULL,
  introduction TEXT NOT NULL,
  portfolio TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TEXT NOT NULL
);

-- 2. Configure Row Level Security (RLS) Policies
-- To allow the static frontend client to interact with the database using the anon key, we configure public policies.

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

-- members Policies
CREATE POLICY "Allow public read members" ON members FOR SELECT USING (true);
CREATE POLICY "Allow public write members" ON members FOR ALL USING (true) WITH CHECK (true);

-- attendance Policies
CREATE POLICY "Allow public read attendance" ON attendance FOR SELECT USING (true);
CREATE POLICY "Allow public write attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);

-- sessions Policies
CREATE POLICY "Allow public read sessions" ON sessions FOR SELECT USING (true);
CREATE POLICY "Allow public write sessions" ON sessions FOR ALL USING (true) WITH CHECK (true);

-- projects Policies
CREATE POLICY "Allow public read projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Allow public write projects" ON projects FOR ALL USING (true) WITH CHECK (true);

-- news Policies
CREATE POLICY "Allow public read news" ON news FOR SELECT USING (true);
CREATE POLICY "Allow public write news" ON news FOR ALL USING (true) WITH CHECK (true);

-- applications Policies (Insert is public, Select/Update is public for admin mode)
CREATE POLICY "Allow public insert applications" ON applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read applications" ON applications FOR SELECT USING (true);
CREATE POLICY "Allow public update applications" ON applications FOR UPDATE USING (true);
